#!/bin/bash

if [ "$#" -ne 4 ]; then
  echo "Probleme dans para_all_folders_start_zero : 1) main_folder_of_folders_of_instances 2) main_folder_where_write_results 3) time_limit_per_algorithm 4) time_limit_per_folder"
  exit 1
fi

timeout $4 bash run_folder_start_zero "$1/graphs-100-200" "$2/graphs-100-200" $3 &
timeout $4 bash run_folder_start_zero "$1/graphs-200-300" "$2/graphs-200-300" $3 &
timeout $4 bash run_folder_start_zero "$1/graphs-300-400" "$2/graphs-300-400" $3 &
timeout $4 bash run_folder_start_zero "$1/graphs-400-500" "$2/graphs-400-500" $3 &
timeout $4 bash run_folder_start_zero "$1/graphs-500-600" "$2/graphs-500-600" $3 &
timeout $4 bash run_folder_start_zero "$1/red-graphs-100-200" "$2/red-graphs-100-200" $3 &
timeout $4 bash run_folder_start_zero "$1/red-graphs-200-300" "$2/red-graphs-200-300" $3 &
timeout $4 bash run_folder_start_zero "$1/red-graphs-300-400" "$2/red-graphs-300-400" $3 &
timeout $4 bash run_folder_start_zero "$1/red-graphs-400-500" "$2/red-graphs-400-500" $3 &
timeout $4 bash run_folder_start_zero "$1/red-graphs-500-600" "$2/red-graphs-500-600" $3 &
wait



