#!/bin/bash

if [ "$#" -ne 4 ]; then
  echo "Probleme dans run_timeout_each_folder : main_folder main_file_results time_limit_file time_limit_folder"
  exit 1
fi

for i in $1/* ; do
  if [ -d "$i" ]; then
    
    folder=$(basename $i)
    #echo $folder
    if [[ ${folder:0:3} =~ "gra" ]]; then 
    
      #graph directory
      timeout $4 bash run_folder $i "$2/c_$folder" c $3 &
      timeout $4 bash run_folder $i "$2/in2_$folder" in2 $3 &
      wait
      
    else 
      if [[ ${folder:0:3} =~ "red" ]]; then
      
        #red graph directory
        timeout $4 bash run_folder $i "$2/c_$folder" c $3 &
        timeout $4 bash run_folder $i "$2/in2_$folder" in2 $3 &
        wait
        
      fi
    fi
    
  fi
done



