#!/bin/bash

if [ "$#" -ne 3 ]; then
  echo "Probleme dans run_folder_start_zero : 1) directory 2) where_to_write_results 3) timeout_per_algorithm"
  exit 1
fi

echo "Working on directory $1 : starting at number 0"

for file in "$1"/*
do
  case "$file" in
  *.graph ) 
        
        #echo "$(basename $file)"
        bash run_mca $file $2 "both-c" $3
        bash run_mca $file $2 "both-in2" $3
        
        ;;
  esac
done
