#!/bin/bash

if [ "$#" -ne 4 ]; then
  echo "Probleme dans run_folder"
  exit 1
fi

echo "Working on directory $1"

for file in "$1"/*
do
  case "$file" in
  *.graph ) 
        #echo "$(basename $file)"
        bash run_mca $file $2 $3 $4
        ;;
  esac
done


