#!/bin/bash

if [ "$#" -ne 4 ]; then
  echo "Probleme dans run_all_folders : main_folder main_file_results what_to_do time_limite_seconds"
  exit 1
fi

for i in $1/* ; do
  if [ -d "$i" ]; then
    
    file=$(basename $i)
    #echo $file
    if [[ ${file:0:3} =~ "gra" ]]; then 
    
      #graph directory
      bash run_folder $i "$2/$3_$file" $3 $4
      
    else 
      if [[ ${file:0:3} =~ "red" ]]; then
      
        #red graph directory
        bash run_folder $i "$2/$3_$file" $3 $4
        
      fi
    fi
    
  fi
done



