#!/bin/bash

if [ "$#" -ne 2 ]; then
  echo "Probleme dans script_Julien : 1) time_limit_per_algo 1) time_limit_per_folder"
  exit 1
fi

# retrieve number of instances that are solved
a=$(wc -l "Results/graphs-200-300" | cut -d " " -f 1)
b=$(wc -l "Results/graphs-300-400" | cut -d " " -f 1)
c=$(wc -l "Results/graphs-400-500" | cut -d " " -f 1)
d=$(wc -l "Results/graphs-500-600" | cut -d " " -f 1)

e=$(wc -l "Results/red-graphs-200-300" | cut -d " " -f 1)
f=$(wc -l "Results/red-graphs-300-400" | cut -d " " -f 1)
g=$(wc -l "Results/red-graphs-400-500" | cut -d " " -f 1)
h=$(wc -l "Results/red-graphs-500-600" | cut -d " " -f 1)

# solve other instances
timeout $2 bash run_folder_start_last "Data_MCA/graphs-200-300" "Results/graphs-200-300" $1 $a &
timeout $2 bash run_folder_start_last "Data_MCA/graphs-300-400" "Results/graphs-300-400" $1 $b &
timeout $2 bash run_folder_start_last "Data_MCA/graphs-400-500" "Results/graphs-400-500" $1 $c &
timeout $2 bash run_folder_start_last "Data_MCA/graphs-500-600" "Results/graphs-500-600" $1 $d &

timeout $2 bash run_folder_start_last "Data_MCA/red-graphs-200-300" "Results/red-graphs-200-300" $1 $e &
timeout $2 bash run_folder_start_last "Data_MCA/red-graphs-300-400" "Results/red-graphs-300-400" $1 $f &
timeout $2 bash run_folder_start_last "Data_MCA/red-graphs-400-500" "Results/red-graphs-400-500" $1 $g &
timeout $2 bash run_folder_start_last "Data_MCA/red-graphs-500-600" "Results/red-graphs-500-600" $1 $h &
wait



